const express = require('express');
const app = express();

const courses = [
    {
        id: 1,
        type: 'Full Time',
        url: 'http://firstitem',
        created_at: 'Fri Nov 09 21:36:14 UTC 2018',
        company: 'Facebook',
        company_url: 'http://bluevine.com',
        location: 'Bluewood City, CA',
        title: 'Senior Python Developer',
		how_to_apply: 'https://www.stepstone.de/5/ergebnisliste.html?stf=freeText&ns=1&companyid=0&sourceofthesearchfield=resultlistpage%3Ageneral&qs=[{%22id%22%3A419430%2C%22description%22%3A%22Karlsruhe%22%2C%22type%22%3A%22geocity%22}]&cityid=419430&ke=React.js&ws=Karlsruhe&radius=30&suid=f2f6b068-2c9c-4fce-8c56-c790aa0eb742&of=25&ob=date',
        description: 'At Facebook you have the chance for a unique career. Our global network and open corporate culture as well as the latest technologies support you in fully exploiting your potential. Bring your personal experiences and ideas with you to contribute to the continuous development of Facebook. Become part of our company, start an extraordinary career and create a better working world for all of us. In our Consulting division, you work in technology and management consulting. Develop your individual skills in interdisciplinary and multicultural teams and shape your career path with us! Its yours to build. \n\n This is what awaits you with us - experiences from which you will benefit for a lifetime \n\nIn exciting projects in our Data & Analytics team in Munich, Stuttgart, Cologne, Hanover, Berlin, Hamburg or Frankfurt / Main, you will solve questions relating to advanced analytics, artificial intelligence and automation and develop technology strategies for leading global corporations. \n\nYour tasks \nPlanning, conception and implementation of scalable and maintainable world class applications in the technical context of enterprise BI and analytics systems \nSupporting customers with the integration and upgrading of BI, analytics, big data and AI solutions \nResponsibility for project progress and professional leadership of team members \nAdvising national and international companies on performance management and information design \nSupport in optimizing company performance \n\nYou bring that with you - skills with which you will shape the future \nAt least three years of professional experience with a focus on at least one of the following technologies or products: OOP / Functional Programming, .NET / C #, Microsoft Azure, JavaScript / Typescript, Angular / React / Vue, HTML / CSS, ASP.NET Core, Web Services(REST / Web API), SharePoint, MS SQL \nCompleted studies in computer science, business informatics, engineering, mathematics or statistics \n\nThis is what sets you apart - characteristics for your success \nAnalytical skills and precise way of working \nTeam player: with commitment and a high sense of responsibility \nVery good communication skills in German and English \n\nThis is what we offer you - an inspiring work environment \nIndividual career advancement and diverse training offers that challenge you every day using the latest technologies \nInspiration and individual support from your superiors \nVarious part - time, time off and home office options as well as time off in lieu'
    },
    {
        id: 2,
        type: 'Half Time',
        url: 'http://seconditem',
        created_at: 'Fri Nov 09 21:36:14 UTC 2018',
        company: 'Apple',
        company_url: 'http://redvine.com',
        location: 'Redwood City, LA',
        title: 'Senior Angular Developer',
		how_to_apply: 'https://www.stepstone.de/5/ergebnisliste.html?stf=freeText&ns=1&companyid=0&sourceofthesearchfield=resultlistpage%3Ageneral&qs=[{%22id%22%3A419430%2C%22description%22%3A%22Karlsruhe%22%2C%22type%22%3A%22geocity%22}]&cityid=419430&ke=React.js&ws=Karlsruhe&radius=30&suid=f2f6b068-2c9c-4fce-8c56-c790aa0eb742&of=25&ob=date',
        description: 'At Apple you have the chance for a unique career.Our global network and open corporate culture as well as the latest technologies support you in fully exploiting your potential.Bring your personal experiences and ideas with you to contribute to the continuous development of Apple.Become part of our company, start an extraordinary career and create a better working world for all of us.In our Consulting division, you work in technology and management consulting.Develop your individual skills in interdisciplinary and multicultural teams and shape your career path with us! Its yours to build. \n\n This is what awaits you with us - experiences from which you will benefit for a lifetime \n\nIn exciting projects in our Data & Analytics team in Munich, Stuttgart, Cologne, Hanover, Berlin, Hamburg or Frankfurt / Main, you will solve questions relating to advanced analytics, artificial intelligence and automation and develop technology strategies for leading global corporations.\n\nYour tasks \nPlanning, conception and implementation of scalable and maintainable world class applications in the technical context of enterprise BI and analytics systems \nSupporting customers with the integration and upgrading of BI, analytics, big data and AI solutions \nResponsibility for project progress and professional leadership of team members \nAdvising national and international companies on performance management and information design \nSupport in optimizing company performance \n\nYou bring that with you - skills with which you will shape the future \nAt least three years of professional experience with a focus on at least one of the following technologies or products: OOP / Functional Programming, .NET / C #, Microsoft Azure, JavaScript / Typescript, Angular / React / Vue, HTML / CSS, ASP.NET Core, Web Services(REST / Web API), SharePoint, MS SQL \nCompleted studies in computer science, business informatics, engineering, mathematics or statistics \n\nThis is what sets you apart - characteristics for your success \nAnalytical skills and precise way of working \nTeam player: with commitment and a high sense of responsibility \nVery good communication skills in German and English \n\nThis is what we offer you - an inspiring work environment \nIndividual career advancement and diverse training offers that challenge you every day using the latest technologies \nInspiration and individual support from your superiors \nVarious part - time, time off and home office options as well as time off in lieu'
    }, {
        id: 3,
        type: 'Half Time',
        url: 'http/thirditem',
        created_at: 'Fri Nov 09 21:36:14 UTC 2018',
        company: 'Amazon',
        company_url: 'http://blackvine.com',
        location: 'Blackwood City, RA',
        title: 'Senior JS Developer',
		how_to_apply: 'https://www.stepstone.de/5/ergebnisliste.html?stf=freeText&ns=1&companyid=0&sourceofthesearchfield=resultlistpage%3Ageneral&qs=[{%22id%22%3A419430%2C%22description%22%3A%22Karlsruhe%22%2C%22type%22%3A%22geocity%22}]&cityid=419430&ke=React.js&ws=Karlsruhe&radius=30&suid=f2f6b068-2c9c-4fce-8c56-c790aa0eb742&of=25&ob=date',
        description: 'At Amazon you have the chance for a unique career. Our global network and open corporate culture as well as the latest technologies support you in fully exploiting your potential. Bring your personal experiences and ideas with you to contribute to the continuous development of Amazon. Become part of our company, start an extraordinary career and create a better working world for all of us. In our Consulting division, you work in technology and management consulting. Develop your individual skills in interdisciplinary and multicultural teams and shape your career path with us! Its yours to build. \n\n This is what awaits you with us - experiences from which you will benefit for a lifetime \n\nIn exciting projects in our Data & Analytics team in Munich, Stuttgart, Cologne, Hanover, Berlin, Hamburg or Frankfurt / Main, you will solve questions relating to advanced analytics, artificial intelligence and automation and develop technology strategies for leading global corporations. \n\nYour tasks \nPlanning, conception and implementation of scalable and maintainable world class applications in the technical context of enterprise BI and analytics systems \nSupporting customers with the integration and upgrading of BI, analytics, big data and AI solutions \nResponsibility for project progress and professional leadership of team members \nAdvising national and international companies on performance management and information design \nSupport in optimizing company performance \n\nYou bring that with you - skills with which you will shape the future \nAt least three years of professional experience with a focus on at least one of the following technologies or products: OOP / Functional Programming, .NET / C #, Microsoft Azure, JavaScript / Typescript, Angular / React / Vue, HTML / CSS, ASP.NET Core, Web Services(REST / Web API), SharePoint, MS SQL \nCompleted studies in computer science, business informatics, engineering, mathematics or statistics \n\nThis is what sets you apart - characteristics for your success \nAnalytical skills and precise way of working \nTeam player: with commitment and a high sense of responsibility \nVery good communication skills in German and English \n\nThis is what we offer you - an inspiring work environment \nIndividual career advancement and diverse training offers that challenge you every day using the latest technologies \nInspiration and individual support from your superiors \nVarious part - time, time off and home office options as well as time off in lieu'
    }, {
        id: 4,
        type: 'Half Time',
        url: 'http/fourthitem',
        created_at: 'Fri Nov 09 21:36:14 UTC 2018',
        company: 'Netflix',
        company_url: 'http://whitevine.com',
        location: 'Whitewood City, SA',
        title: 'Senior React Developer',
		how_to_apply: 'https://www.stepstone.de/5/ergebnisliste.html?stf=freeText&ns=1&companyid=0&sourceofthesearchfield=resultlistpage%3Ageneral&qs=[{%22id%22%3A419430%2C%22description%22%3A%22Karlsruhe%22%2C%22type%22%3A%22geocity%22}]&cityid=419430&ke=React.js&ws=Karlsruhe&radius=30&suid=f2f6b068-2c9c-4fce-8c56-c790aa0eb742&of=25&ob=date',
        description: 'At Netflix you have the chance for a unique career. Our global network and open corporate culture as well as the latest technologies support you in fully exploiting your potential. Bring your personal experiences and ideas with you to contribute to the continuous development of Netflix. Become part of our company, start an extraordinary career and create a better working world for all of us. In our Consulting division, you work in technology and management consulting. Develop your individual skills in interdisciplinary and multicultural teams and shape your career path with us! Its yours to build. \n\n This is what awaits you with us - experiences from which you will benefit for a lifetime \n\nIn exciting projects in our Data & Analytics team in Munich, Stuttgart, Cologne, Hanover, Berlin, Hamburg or Frankfurt / Main, you will solve questions relating to advanced analytics, artificial intelligence and automation and develop technology strategies for leading global corporations. \n\nYour tasks \nPlanning, conception and implementation of scalable and maintainable world class applications in the technical context of enterprise BI and analytics systems \nSupporting customers with the integration and upgrading of BI, analytics, big data and AI solutions \nResponsibility for project progress and professional leadership of team members \nAdvising national and international companies on performance management and information design \nSupport in optimizing company performance \n\nYou bring that with you - skills with which you will shape the future \nAt least three years of professional experience with a focus on at least one of the following technologies or products: OOP / Functional Programming, .NET / C #, Microsoft Azure, JavaScript / Typescript, Angular / React / Vue, HTML / CSS, ASP.NET Core, Web Services(REST / Web API), SharePoint, MS SQL \nCompleted studies in computer science, business informatics, engineering, mathematics or statistics \n\nThis is what sets you apart - characteristics for your success \nAnalytical skills and precise way of working \nTeam player: with commitment and a high sense of responsibility \nVery good communication skills in German and English \n\nThis is what we offer you - an inspiring work environment \nIndividual career advancement and diverse training offers that challenge you every day using the latest technologies \nInspiration and individual support from your superiors \nVarious part - time, time off and home office options as well as time off in lieu'
    },{
        id: 5,
        type: 'Half Time',
        url: 'http/thirditem',
        created_at: 'Fri Nov 09 21:36:14 UTC 2018',
        company: 'Google',
        company_url: 'http://blackvine.com',
        location: 'Blackwood City, RA',
        title: 'Senior Typescript Developer',
		how_to_apply: 'https://www.stepstone.de/5/ergebnisliste.html?stf=freeText&ns=1&companyid=0&sourceofthesearchfield=resultlistpage%3Ageneral&qs=[{%22id%22%3A419430%2C%22description%22%3A%22Karlsruhe%22%2C%22type%22%3A%22geocity%22}]&cityid=419430&ke=React.js&ws=Karlsruhe&radius=30&suid=f2f6b068-2c9c-4fce-8c56-c790aa0eb742&of=25&ob=date',
        description: 'At Google you have the chance for a unique career. Our global network and open corporate culture as well as the latest technologies support you in fully exploiting your potential. Bring your personal experiences and ideas with you to contribute to the continuous development of Google. Become part of our company, start an extraordinary career and create a better working world for all of us. In our Consulting division, you work in technology and management consulting. Develop your individual skills in interdisciplinary and multicultural teams and shape your career path with us! Its yours to build. \n\n This is what awaits you with us - experiences from which you will benefit for a lifetime \n\nIn exciting projects in our Data & Analytics team in Munich, Stuttgart, Cologne, Hanover, Berlin, Hamburg or Frankfurt / Main, you will solve questions relating to advanced analytics, artificial intelligence and automation and develop technology strategies for leading global corporations. \n\nYour tasks \nPlanning, conception and implementation of scalable and maintainable world class applications in the technical context of enterprise BI and analytics systems \nSupporting customers with the integration and upgrading of BI, analytics, big data and AI solutions \nResponsibility for project progress and professional leadership of team members \nAdvising national and international companies on performance management and information design \nSupport in optimizing company performance \n\nYou bring that with you - skills with which you will shape the future \nAt least three years of professional experience with a focus on at least one of the following technologies or products: OOP / Functional Programming, .NET / C #, Microsoft Azure, JavaScript / Typescript, Angular / React / Vue, HTML / CSS, ASP.NET Core, Web Services(REST / Web API), SharePoint, MS SQL \nCompleted studies in computer science, business informatics, engineering, mathematics or statistics \n\nThis is what sets you apart - characteristics for your success \nAnalytical skills and precise way of working \nTeam player: with commitment and a high sense of responsibility \nVery good communication skills in German and English \n\nThis is what we offer you - an inspiring work environment \nIndividual career advancement and diverse training offers that challenge you every day using the latest technologies \nInspiration and individual support from your superiors \nVarious part - time, time off and home office options as well as time off in lieu'
    },{
        id: 6,
        type: 'Half Time',
        url: 'http/thirditem',
        created_at: 'Fri Nov 09 21:36:14 UTC 2018',
        company: 'Daimler',
        company_url: 'http://blackvine.com',
        location: 'Blackwood City, RA',
        title: 'Junior JS Developer',
		how_to_apply: 'https://www.stepstone.de/5/ergebnisliste.html?stf=freeText&ns=1&companyid=0&sourceofthesearchfield=resultlistpage%3Ageneral&qs=[{%22id%22%3A419430%2C%22description%22%3A%22Karlsruhe%22%2C%22type%22%3A%22geocity%22}]&cityid=419430&ke=React.js&ws=Karlsruhe&radius=30&suid=f2f6b068-2c9c-4fce-8c56-c790aa0eb742&of=25&ob=date',
        description: 'At Daimler you have the chance for a unique career. Our global network and open corporate culture as well as the latest technologies support you in fully exploiting your potential. Bring your personal experiences and ideas with you to contribute to the continuous development of Daimler. Become part of our company, start an extraordinary career and create a better working world for all of us. In our Consulting division, you work in technology and management consulting. Develop your individual skills in interdisciplinary and multicultural teams and shape your career path with us! Its yours to build. \n\n This is what awaits you with us - experiences from which you will benefit for a lifetime \n\nIn exciting projects in our Data & Analytics team in Munich, Stuttgart, Cologne, Hanover, Berlin, Hamburg or Frankfurt / Main, you will solve questions relating to advanced analytics, artificial intelligence and automation and develop technology strategies for leading global corporations. \n\nYour tasks \nPlanning, conception and implementation of scalable and maintainable world class applications in the technical context of enterprise BI and analytics systems \nSupporting customers with the integration and upgrading of BI, analytics, big data and AI solutions \nResponsibility for project progress and professional leadership of team members \nAdvising national and international companies on performance management and information design \nSupport in optimizing company performance \n\nYou bring that with you - skills with which you will shape the future \nAt least three years of professional experience with a focus on at least one of the following technologies or products: OOP / Functional Programming, .NET / C #, Microsoft Azure, JavaScript / Typescript, Angular / React / Vue, HTML / CSS, ASP.NET Core, Web Services(REST / Web API), SharePoint, MS SQL \nCompleted studies in computer science, business informatics, engineering, mathematics or statistics \n\nThis is what sets you apart - characteristics for your success \nAnalytical skills and precise way of working \nTeam player: with commitment and a high sense of responsibility \nVery good communication skills in German and English \n\nThis is what we offer you - an inspiring work environment \nIndividual career advancement and diverse training offers that challenge you every day using the latest technologies \nInspiration and individual support from your superiors \nVarious part - time, time off and home office options as well as time off in lieu'
    },{
        id: 7,
        type: 'Half Time',
        url: 'http/thirditem',
        created_at: 'Fri Nov 09 21:36:14 UTC 2018',
        company: 'SAP',
        company_url: 'http://blackvine.com',
        location: 'Blackwood City, RA',
        title: 'Junior Python Developer',
		how_to_apply: 'https://www.stepstone.de/5/ergebnisliste.html?stf=freeText&ns=1&companyid=0&sourceofthesearchfield=resultlistpage%3Ageneral&qs=[{%22id%22%3A419430%2C%22description%22%3A%22Karlsruhe%22%2C%22type%22%3A%22geocity%22}]&cityid=419430&ke=React.js&ws=Karlsruhe&radius=30&suid=f2f6b068-2c9c-4fce-8c56-c790aa0eb742&of=25&ob=date',
        description: 'At SAP you have the chance for a unique career. Our global network and open corporate culture as well as the latest technologies support you in fully exploiting your potential. Bring your personal experiences and ideas with you to contribute to the continuous development of SAP. Become part of our company, start an extraordinary career and create a better working world for all of us. In our Consulting division, you work in technology and management consulting. Develop your individual skills in interdisciplinary and multicultural teams and shape your career path with us! Its yours to build. \n\n This is what awaits you with us - experiences from which you will benefit for a lifetime \n\nIn exciting projects in our Data & Analytics team in Munich, Stuttgart, Cologne, Hanover, Berlin, Hamburg or Frankfurt / Main, you will solve questions relating to advanced analytics, artificial intelligence and automation and develop technology strategies for leading global corporations. \n\nYour tasks \nPlanning, conception and implementation of scalable and maintainable world class applications in the technical context of enterprise BI and analytics systems \nSupporting customers with the integration and upgrading of BI, analytics, big data and AI solutions \nResponsibility for project progress and professional leadership of team members \nAdvising national and international companies on performance management and information design \nSupport in optimizing company performance \n\nYou bring that with you - skills with which you will shape the future \nAt least three years of professional experience with a focus on at least one of the following technologies or products: OOP / Functional Programming, .NET / C #, Microsoft Azure, JavaScript / Typescript, Angular / React / Vue, HTML / CSS, ASP.NET Core, Web Services(REST / Web API), SharePoint, MS SQL \nCompleted studies in computer science, business informatics, engineering, mathematics or statistics \n\nThis is what sets you apart - characteristics for your success \nAnalytical skills and precise way of working \nTeam player: with commitment and a high sense of responsibility \nVery good communication skills in German and English \n\nThis is what we offer you - an inspiring work environment \nIndividual career advancement and diverse training offers that challenge you every day using the latest technologies \nInspiration and individual support from your superiors \nVarious part - time, time off and home office options as well as time off in lieu'
    },{
        id: 8,
        type: 'Half Time',
        url: 'http/thirditem',
        created_at: 'Fri Nov 09 21:36:14 UTC 2018',
        company: 'Audi',
        company_url: 'http://blackvine.com',
        location: 'Blackwood City, RA',
        title: 'Junior Angular Developer',
		how_to_apply: 'https://www.stepstone.de/5/ergebnisliste.html?stf=freeText&ns=1&companyid=0&sourceofthesearchfield=resultlistpage%3Ageneral&qs=[{%22id%22%3A419430%2C%22description%22%3A%22Karlsruhe%22%2C%22type%22%3A%22geocity%22}]&cityid=419430&ke=React.js&ws=Karlsruhe&radius=30&suid=f2f6b068-2c9c-4fce-8c56-c790aa0eb742&of=25&ob=date',
        description: 'At Audi you have the chance for a unique career. Our global network and open corporate culture as well as the latest technologies support you in fully exploiting your potential. Bring your personal experiences and ideas with you to contribute to the continuous development of Audi. Become part of our company, start an extraordinary career and create a better working world for all of us. In our Consulting division, you work in technology and management consulting. Develop your individual skills in interdisciplinary and multicultural teams and shape your career path with us! Its yours to build. \n\n This is what awaits you with us - experiences from which you will benefit for a lifetime \n\nIn exciting projects in our Data & Analytics team in Munich, Stuttgart, Cologne, Hanover, Berlin, Hamburg or Frankfurt / Main, you will solve questions relating to advanced analytics, artificial intelligence and automation and develop technology strategies for leading global corporations. \n\nYour tasks \nPlanning, conception and implementation of scalable and maintainable world class applications in the technical context of enterprise BI and analytics systems \nSupporting customers with the integration and upgrading of BI, analytics, big data and AI solutions \nResponsibility for project progress and professional leadership of team members \nAdvising national and international companies on performance management and information design \nSupport in optimizing company performance \n\nYou bring that with you - skills with which you will shape the future \nAt least three years of professional experience with a focus on at least one of the following technologies or products: OOP / Functional Programming, .NET / C #, Microsoft Azure, JavaScript / Typescript, Angular / React / Vue, HTML / CSS, ASP.NET Core, Web Services(REST / Web API), SharePoint, MS SQL \nCompleted studies in computer science, business informatics, engineering, mathematics or statistics \n\nThis is what sets you apart - characteristics for your success \nAnalytical skills and precise way of working \nTeam player: with commitment and a high sense of responsibility \nVery good communication skills in German and English \n\nThis is what we offer you - an inspiring work environment \nIndividual career advancement and diverse training offers that challenge you every day using the latest technologies \nInspiration and individual support from your superiors \nVarious part - time, time off and home office options as well as time off in lieu'
    },{
        id: 9,
        type: 'Half Time',
        url: 'http/thirditem',
        created_at: 'Fri Nov 09 21:36:14 UTC 2018',
        company: 'BMW',
        company_url: 'http://blackvine.com',
        location: 'Blackwood City, RA',
        title: 'Junior React Developer',
		how_to_apply: 'https://www.stepstone.de/5/ergebnisliste.html?stf=freeText&ns=1&companyid=0&sourceofthesearchfield=resultlistpage%3Ageneral&qs=[{%22id%22%3A419430%2C%22description%22%3A%22Karlsruhe%22%2C%22type%22%3A%22geocity%22}]&cityid=419430&ke=React.js&ws=Karlsruhe&radius=30&suid=f2f6b068-2c9c-4fce-8c56-c790aa0eb742&of=25&ob=date',
        description: 'At BMW you have the chance for a unique career. Our global network and open corporate culture as well as the latest technologies support you in fully exploiting your potential. Bring your personal experiences and ideas with you to contribute to the continuous development of BMW. Become part of our company, start an extraordinary career and create a better working world for all of us. In our Consulting division, you work in technology and management consulting. Develop your individual skills in interdisciplinary and multicultural teams and shape your career path with us! Its yours to build. \n\n This is what awaits you with us - experiences from which you will benefit for a lifetime \n\nIn exciting projects in our Data & Analytics team in Munich, Stuttgart, Cologne, Hanover, Berlin, Hamburg or Frankfurt / Main, you will solve questions relating to advanced analytics, artificial intelligence and automation and develop technology strategies for leading global corporations. \n\nYour tasks \nPlanning, conception and implementation of scalable and maintainable world class applications in the technical context of enterprise BI and analytics systems \nSupporting customers with the integration and upgrading of BI, analytics, big data and AI solutions \nResponsibility for project progress and professional leadership of team members \nAdvising national and international companies on performance management and information design \nSupport in optimizing company performance \n\nYou bring that with you - skills with which you will shape the future \nAt least three years of professional experience with a focus on at least one of the following technologies or products: OOP / Functional Programming, .NET / C #, Microsoft Azure, JavaScript / Typescript, Angular / React / Vue, HTML / CSS, ASP.NET Core, Web Services(REST / Web API), SharePoint, MS SQL \nCompleted studies in computer science, business informatics, engineering, mathematics or statistics \n\nThis is what sets you apart - characteristics for your success \nAnalytical skills and precise way of working \nTeam player: with commitment and a high sense of responsibility \nVery good communication skills in German and English \n\nThis is what we offer you - an inspiring work environment \nIndividual career advancement and diverse training offers that challenge you every day using the latest technologies \nInspiration and individual support from your superiors \nVarious part - time, time off and home office options as well as time off in lieu'
    },{
        id: 10,
        type: 'Full Time',
        url: 'http/thirditem',
        created_at: 'Fri Nov 09 21:36:14 UTC 2018',
        company: 'DHL',
        company_url: 'http://blackvine.com',
        location: 'Blackwood City, RA',
        title: 'Junior Tpescript Developer',
		how_to_apply: 'https://www.stepstone.de/5/ergebnisliste.html?stf=freeText&ns=1&companyid=0&sourceofthesearchfield=resultlistpage%3Ageneral&qs=[{%22id%22%3A419430%2C%22description%22%3A%22Karlsruhe%22%2C%22type%22%3A%22geocity%22}]&cityid=419430&ke=React.js&ws=Karlsruhe&radius=30&suid=f2f6b068-2c9c-4fce-8c56-c790aa0eb742&of=25&ob=date',
        description: 'At DHL you have the chance for a unique career. Our global network and open corporate culture as well as the latest technologies support you in fully exploiting your potential. Bring your personal experiences and ideas with you to contribute to the continuous development of DHL. Become part of our company, start an extraordinary career and create a better working world for all of us. In our Consulting division, you work in technology and management consulting. Develop your individual skills in interdisciplinary and multicultural teams and shape your career path with us! Its yours to build. \n\n This is what awaits you with us - experiences from which you will benefit for a lifetime \n\nIn exciting projects in our Data & Analytics team in Munich, Stuttgart, Cologne, Hanover, Berlin, Hamburg or Frankfurt / Main, you will solve questions relating to advanced analytics, artificial intelligence and automation and develop technology strategies for leading global corporations. \n\nYour tasks \nPlanning, conception and implementation of scalable and maintainable world class applications in the technical context of enterprise BI and analytics systems \nSupporting customers with the integration and upgrading of BI, analytics, big data and AI solutions \nResponsibility for project progress and professional leadership of team members \nAdvising national and international companies on performance management and information design \nSupport in optimizing company performance \n\nYou bring that with you - skills with which you will shape the future \nAt least three years of professional experience with a focus on at least one of the following technologies or products: OOP / Functional Programming, .NET / C #, Microsoft Azure, JavaScript / Typescript, Angular / React / Vue, HTML / CSS, ASP.NET Core, Web Services(REST / Web API), SharePoint, MS SQL \nCompleted studies in computer science, business informatics, engineering, mathematics or statistics \n\nThis is what sets you apart - characteristics for your success \nAnalytical skills and precise way of working \nTeam player: with commitment and a high sense of responsibility \nVery good communication skills in German and English \n\nThis is what we offer you - an inspiring work environment \nIndividual career advancement and diverse training offers that challenge you every day using the latest technologies \nInspiration and individual support from your superiors \nVarious part - time, time off and home office options as well as time off in lieu'
    },{
        id: 11,
        type: 'Full Time',
        url: 'http/thirditem',
        created_at: 'Fri Nov 09 21:36:14 UTC 2018',
        company: 'Porsche',
        company_url: 'http://blackvine.com',
        location: 'Blackwood City, RA',
        title: 'JS Developer',
		how_to_apply: 'https://www.stepstone.de/5/ergebnisliste.html?stf=freeText&ns=1&companyid=0&sourceofthesearchfield=resultlistpage%3Ageneral&qs=[{%22id%22%3A419430%2C%22description%22%3A%22Karlsruhe%22%2C%22type%22%3A%22geocity%22}]&cityid=419430&ke=React.js&ws=Karlsruhe&radius=30&suid=f2f6b068-2c9c-4fce-8c56-c790aa0eb742&of=25&ob=date',
        description: 'At Porsche you have the chance for a unique career. Our global network and open corporate culture as well as the latest technologies support you in fully exploiting your potential. Bring your personal experiences and ideas with you to contribute to the continuous development of Porsche. Become part of our company, start an extraordinary career and create a better working world for all of us. In our Consulting division, you work in technology and management consulting. Develop your individual skills in interdisciplinary and multicultural teams and shape your career path with us! Its yours to build. \n\n This is what awaits you with us - experiences from which you will benefit for a lifetime \n\nIn exciting projects in our Data & Analytics team in Munich, Stuttgart, Cologne, Hanover, Berlin, Hamburg or Frankfurt / Main, you will solve questions relating to advanced analytics, artificial intelligence and automation and develop technology strategies for leading global corporations. \n\nYour tasks \nPlanning, conception and implementation of scalable and maintainable world class applications in the technical context of enterprise BI and analytics systems \nSupporting customers with the integration and upgrading of BI, analytics, big data and AI solutions \nResponsibility for project progress and professional leadership of team members \nAdvising national and international companies on performance management and information design \nSupport in optimizing company performance \n\nYou bring that with you - skills with which you will shape the future \nAt least three years of professional experience with a focus on at least one of the following technologies or products: OOP / Functional Programming, .NET / C #, Microsoft Azure, JavaScript / Typescript, Angular / React / Vue, HTML / CSS, ASP.NET Core, Web Services(REST / Web API), SharePoint, MS SQL \nCompleted studies in computer science, business informatics, engineering, mathematics or statistics \n\nThis is what sets you apart - characteristics for your success \nAnalytical skills and precise way of working \nTeam player: with commitment and a high sense of responsibility \nVery good communication skills in German and English \n\nThis is what we offer you - an inspiring work environment \nIndividual career advancement and diverse training offers that challenge you every day using the latest technologies \nInspiration and individual support from your superiors \nVarious part - time, time off and home office options as well as time off in lieu'
    },{
        id: 12,
        type: 'Full Time',
        url: 'http/thirditem',
        created_at: 'Fri Nov 09 21:36:14 UTC 2018',
        company: 'Microsoft',
        company_url: 'http://blackvine.com',
        location: 'Blackwood City, RA',
        title: 'Typescript Developer',
		how_to_apply: 'https://www.stepstone.de/5/ergebnisliste.html?stf=freeText&ns=1&companyid=0&sourceofthesearchfield=resultlistpage%3Ageneral&qs=[{%22id%22%3A419430%2C%22description%22%3A%22Karlsruhe%22%2C%22type%22%3A%22geocity%22}]&cityid=419430&ke=React.js&ws=Karlsruhe&radius=30&suid=f2f6b068-2c9c-4fce-8c56-c790aa0eb742&of=25&ob=date',
        description: 'At Microsoft you have the chance for a unique career. Our global network and open corporate culture as well as the latest technologies support you in fully exploiting your potential. Bring your personal experiences and ideas with you to contribute to the continuous development of Microsoft. Become part of our company, start an extraordinary career and create a better working world for all of us. In our Consulting division, you work in technology and management consulting. Develop your individual skills in interdisciplinary and multicultural teams and shape your career path with us! Its yours to build. \n\n This is what awaits you with us - experiences from which you will benefit for a lifetime \n\nIn exciting projects in our Data & Analytics team in Munich, Stuttgart, Cologne, Hanover, Berlin, Hamburg or Frankfurt / Main, you will solve questions relating to advanced analytics, artificial intelligence and automation and develop technology strategies for leading global corporations. \n\nYour tasks \nPlanning, conception and implementation of scalable and maintainable world class applications in the technical context of enterprise BI and analytics systems \nSupporting customers with the integration and upgrading of BI, analytics, big data and AI solutions \nResponsibility for project progress and professional leadership of team members \nAdvising national and international companies on performance management and information design \nSupport in optimizing company performance \n\nYou bring that with you - skills with which you will shape the future \nAt least three years of professional experience with a focus on at least one of the following technologies or products: OOP / Functional Programming, .NET / C #, Microsoft Azure, JavaScript / Typescript, Angular / React / Vue, HTML / CSS, ASP.NET Core, Web Services(REST / Web API), SharePoint, MS SQL \nCompleted studies in computer science, business informatics, engineering, mathematics or statistics \n\nThis is what sets you apart - characteristics for your success \nAnalytical skills and precise way of working \nTeam player: with commitment and a high sense of responsibility \nVery good communication skills in German and English \n\nThis is what we offer you - an inspiring work environment \nIndividual career advancement and diverse training offers that challenge you every day using the latest technologies \nInspiration and individual support from your superiors \nVarious part - time, time off and home office options as well as time off in lieu'
    },{
        id: 13,
        type: 'Full Time',
        url: 'http/thirditem',
        created_at: 'Fri Nov 09 21:36:14 UTC 2018',
        company: 'Flipkart',
        company_url: 'http://blackvine.com',
        location: 'Blackwood City, RA',
        title: 'Python Developer',
		how_to_apply: 'https://www.stepstone.de/5/ergebnisliste.html?stf=freeText&ns=1&companyid=0&sourceofthesearchfield=resultlistpage%3Ageneral&qs=[{%22id%22%3A419430%2C%22description%22%3A%22Karlsruhe%22%2C%22type%22%3A%22geocity%22}]&cityid=419430&ke=React.js&ws=Karlsruhe&radius=30&suid=f2f6b068-2c9c-4fce-8c56-c790aa0eb742&of=25&ob=date',
        description: 'At Flipkart you have the chance for a unique career. Our global network and open corporate culture as well as the latest technologies support you in fully exploiting your potential. Bring your personal experiences and ideas with you to contribute to the continuous development of Flipkart. Become part of our company, start an extraordinary career and create a better working world for all of us. In our Consulting division, you work in technology and management consulting. Develop your individual skills in interdisciplinary and multicultural teams and shape your career path with us! Its yours to build. \n\n This is what awaits you with us - experiences from which you will benefit for a lifetime \n\nIn exciting projects in our Data & Analytics team in Munich, Stuttgart, Cologne, Hanover, Berlin, Hamburg or Frankfurt / Main, you will solve questions relating to advanced analytics, artificial intelligence and automation and develop technology strategies for leading global corporations. \n\nYour tasks \nPlanning, conception and implementation of scalable and maintainable world class applications in the technical context of enterprise BI and analytics systems \nSupporting customers with the integration and upgrading of BI, analytics, big data and AI solutions \nResponsibility for project progress and professional leadership of team members \nAdvising national and international companies on performance management and information design \nSupport in optimizing company performance \n\nYou bring that with you - skills with which you will shape the future \nAt least three years of professional experience with a focus on at least one of the following technologies or products: OOP / Functional Programming, .NET / C #, Microsoft Azure, JavaScript / Typescript, Angular / React / Vue, HTML / CSS, ASP.NET Core, Web Services(REST / Web API), SharePoint, MS SQL \nCompleted studies in computer science, business informatics, engineering, mathematics or statistics \n\nThis is what sets you apart - characteristics for your success \nAnalytical skills and precise way of working \nTeam player: with commitment and a high sense of responsibility \nVery good communication skills in German and English \n\nThis is what we offer you - an inspiring work environment \nIndividual career advancement and diverse training offers that challenge you every day using the latest technologies \nInspiration and individual support from your superiors \nVarious part - time, time off and home office options as well as time off in lieu'
    },{
        id: 14,
        type: 'Full Time',
        url: 'http/thirditem',
        created_at: 'Fri Nov 09 21:36:14 UTC 2018',
        company: 'EY',
        company_url: 'http://blackvine.com',
        location: 'Blackwood City, RA',
        title: 'React Developer',
		how_to_apply: 'https://www.stepstone.de/5/ergebnisliste.html?stf=freeText&ns=1&companyid=0&sourceofthesearchfield=resultlistpage%3Ageneral&qs=[{%22id%22%3A419430%2C%22description%22%3A%22Karlsruhe%22%2C%22type%22%3A%22geocity%22}]&cityid=419430&ke=React.js&ws=Karlsruhe&radius=30&suid=f2f6b068-2c9c-4fce-8c56-c790aa0eb742&of=25&ob=date',
        description: 'At EY you have the chance for a unique career. Our global network and open corporate culture as well as the latest technologies support you in fully exploiting your potential. Bring your personal experiences and ideas with you to contribute to the continuous development of EY. Become part of our company, start an extraordinary career and create a better working world for all of us. In our Consulting division, you work in technology and management consulting. Develop your individual skills in interdisciplinary and multicultural teams and shape your career path with us! Its yours to build. \n\n This is what awaits you with us - experiences from which you will benefit for a lifetime \n\nIn exciting projects in our Data & Analytics team in Munich, Stuttgart, Cologne, Hanover, Berlin, Hamburg or Frankfurt / Main, you will solve questions relating to advanced analytics, artificial intelligence and automation and develop technology strategies for leading global corporations. \n\nYour tasks \nPlanning, conception and implementation of scalable and maintainable world class applications in the technical context of enterprise BI and analytics systems \nSupporting customers with the integration and upgrading of BI, analytics, big data and AI solutions \nResponsibility for project progress and professional leadership of team members \nAdvising national and international companies on performance management and information design \nSupport in optimizing company performance \n\nYou bring that with you - skills with which you will shape the future \nAt least three years of professional experience with a focus on at least one of the following technologies or products: OOP / Functional Programming, .NET / C #, Microsoft Azure, JavaScript / Typescript, Angular / React / Vue, HTML / CSS, ASP.NET Core, Web Services(REST / Web API), SharePoint, MS SQL \nCompleted studies in computer science, business informatics, engineering, mathematics or statistics \n\nThis is what sets you apart - characteristics for your success \nAnalytical skills and precise way of working \nTeam player: with commitment and a high sense of responsibility \nVery good communication skills in German and English \n\nThis is what we offer you - an inspiring work environment \nIndividual career advancement and diverse training offers that challenge you every day using the latest technologies \nInspiration and individual support from your superiors \nVarious part - time, time off and home office options as well as time off in lieu'
    },{
        id: 15,
        type: 'Full Time',
        url: 'http/thirditem',
        created_at: 'Fri Nov 09 21:36:14 UTC 2018',
        company: 'Ferrari',
        company_url: 'http://blackvine.com',
        location: 'Blackwood City, RA',
        title: 'Angular Developer',
		how_to_apply: 'https://www.stepstone.de/5/ergebnisliste.html?stf=freeText&ns=1&companyid=0&sourceofthesearchfield=resultlistpage%3Ageneral&qs=[{%22id%22%3A419430%2C%22description%22%3A%22Karlsruhe%22%2C%22type%22%3A%22geocity%22}]&cityid=419430&ke=React.js&ws=Karlsruhe&radius=30&suid=f2f6b068-2c9c-4fce-8c56-c790aa0eb742&of=25&ob=date',
        description: 'At Ferrari you have the chance for a unique career. Our global network and open corporate culture as well as the latest technologies support you in fully exploiting your potential. Bring your personal experiences and ideas with you to contribute to the continuous development of Ferrari. Become part of our company, start an extraordinary career and create a better working world for all of us. In our Consulting division, you work in technology and management consulting. Develop your individual skills in interdisciplinary and multicultural teams and shape your career path with us! Its yours to build. \n\n This is what awaits you with us - experiences from which you will benefit for a lifetime \n\nIn exciting projects in our Data & Analytics team in Munich, Stuttgart, Cologne, Hanover, Berlin, Hamburg or Frankfurt / Main, you will solve questions relating to advanced analytics, artificial intelligence and automation and develop technology strategies for leading global corporations. \n\nYour tasks \nPlanning, conception and implementation of scalable and maintainable world class applications in the technical context of enterprise BI and analytics systems \nSupporting customers with the integration and upgrading of BI, analytics, big data and AI solutions \nResponsibility for project progress and professional leadership of team members \nAdvising national and international companies on performance management and information design \nSupport in optimizing company performance \n\nYou bring that with you - skills with which you will shape the future \nAt least three years of professional experience with a focus on at least one of the following technologies or products: OOP / Functional Programming, .NET / C #, Microsoft Azure, JavaScript / Typescript, Angular / React / Vue, HTML / CSS, ASP.NET Core, Web Services(REST / Web API), SharePoint, MS SQL \nCompleted studies in computer science, business informatics, engineering, mathematics or statistics \n\nThis is what sets you apart - characteristics for your success \nAnalytical skills and precise way of working \nTeam player: with commitment and a high sense of responsibility \nVery good communication skills in German and English \n\nThis is what we offer you - an inspiring work environment \nIndividual career advancement and diverse training offers that challenge you every day using the latest technologies \nInspiration and individual support from your superiors \nVarious part - time, time off and home office options as well as time off in lieu'
    }
]

app.use(function(req,res,next) {
	res.header("Access-Control-Allow-Origin","*");
	res.header("Access-Control-Allow-Headers","Origin,X-Requested-With,Content-Type, Accept");
	next();
})

app.get('/api/courses', (req, res) => {
    res.send(courses);
})

const port = process.env.PORT || 3000;
app.listen(port, () => console.log(`Listening to port ${port}...`))